version: '3'

x-common-environment: &x-common-environment
  SERVER_ENV: ${SERVER_ENV:-dev}
  DOCKER_DATA_DIR: ./docker-data
  DOCKER_BASE_DIR: /var/app/intrawiki/docker-data
  DOCKER_DATA_BASE_DIR: /var/app/intrawiki/docker-data
  DOCKER_HOST_INTERNAL: ${DOCKER_HOST_INTERNAL:-127.0.0.1}
  SERVER_PORT: ${SERVER_PORT:-4000}

services:
  api:
    build:
      context: docker/api
    restart: "no"
    volumes:
      - $DOCKER_DATA_DIR/api:$DOCKER_BASE_DIR/api
    environment:
      <<: *x-common-environment
      OPENAPI_PACKAGE: ${OPENAPI_PACKAGE:-openapi}
      OPENAPI_YAML_DIR: ${OPENAPI_YAML_DIR:-$DOCKER_BASE_DIR/api}
      OPENAPI_YAML_FILE: ${OPENAPI_YAML_FILE:-$DOCKER_BASE_DIR/api/openapi.yaml}
      OPENAPI_OUT_DIR: ${OPENAPI_OUT_DIR:-$DOCKER_BASE_DIR/api/generated}
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    environment:
      <<: *x-common-environment
      REACT_APP_MANAGE_PATH: /intrawiki-manage
    volumes:
      - $DOCKER_DATA_DIR/server/tmp/db:$DOCKER_BASE_DIR/server/tmp/db
    ports:
      - ${SERVER_PORT:-80}:4000
  standalone:
    build:
      context: .
      dockerfile: docker/standalone/Dockerfile
    environment:
      <<: *x-common-environment
      REACT_APP_MANAGE_PATH: /intrawiki-manage
      NODE_ENV: production
      SERVER_PORT: 80
      SESSION_SECURE: "false"
    volumes:
      - ./tmp/db:/var/app/intrawiki/server/tmp/db
    ports:
      - 80:4000
volumes:
  server-pnpm-volume:
  server-node-modules-volume:
  cert-letsencrypt-volume:
