/* tslint:disable */
/* eslint-disable */
/**
 * intrawiki
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    loggedIn: boolean;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    redirectUrl?: string;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "loggedIn" in value;

    return isInstance;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'loggedIn': json['loggedIn'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'redirectUrl': !exists(json, 'redirectUrl') ? undefined : json['redirectUrl'],
    };
}

export function LoginResponseToJSON(value?: LoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'loggedIn': value.loggedIn,
        'userId': value.userId,
        'account': value.account,
        'redirectUrl': value.redirectUrl,
    };
}

